language: java
sudo: false
jdk:
  - oraclejdk8

cache:
  directories:
  - .autoconf

  # Local Maven repository.
  - $HOME/.m2

  # Local builds of zinc (Scala incremental compiler).
  - $HOME/.zinc

# Run the tests and generate coverage reports in one go.
script: mvn scoverage:report

after_success:
  - .travis/publish_docs.sh

  # Upload coverage report to Coveralls.
  - mvn coveralls:report

env:
  global:
    # GH_TOKEN for .travis/publish_docs.sh.
    secure: ffCremJXhnrGEaP0nRgChQiaZrfDJpG8yyMckri/dcTYZsESa0qcyyu9gNXwtW3UkEZpmwFbMSUqkMHgIsYBMDMD9zZLHUpMLswN6VDl3/WrE+4o7tJq8PGDB/idPnM+vr4YPO8uopUGGIhEiAHsvBGqybYsHdGQa1TKmbH0x+k=

notifications:
  slack:
    secure: MpSRYjcajUOegCpk5dzpG0lCe5YBwzlVYTo4b0MD3gu7HFHGFscf2CW1DlP3QJTdaTjxU2oA9nEOvrxq1RZ9J91hwDV5PtZXY5CdVRl9B6VrfulSGT35qeZoaiL0ETfNhfklPTEEiE7xSRG0sYsisqlCl5xN0QqBqrE0yzVHsRA=
